#!/bin/bash
#

# Check if running as root
if [[ "$EUID" -ne 0 ]]; then
  echo "This script should be run as root."
  echo "Aborted"
  exit 1
fi

# Build ISO
mkarchiso -w /tmp/archiso-tmp-dgpu -o . -v profile

